project:
  type: website

website:
  description: "A blog built with Quarto"
  site-url: https://vucka7.github.io/blog/
  title: "Reproducible research course"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/
      - icon: bluesky
        href: https://bsky.app/
format:
  html:
    theme:
      light: flatly
      dark: darkly
    css: styles.css

execute:
  freeze: auto



