project:
  type: website

website:
  description: "A blog built with Quarto"
  site-url: https://vucka7.github.io/blog/
  title: "Swedish Valhund"
  navbar:
    right:
      - about.qmd
format:
  html:
    theme:
      light: flatly
      dark: darkly
    css: styles.css

execute:
  freeze: auto



